version: '3.7'

networks:
  main:
    name: redis-streams-main
    external: true

services:
  redis:
    image: redis:6.2.7
    networks:
      - main

  simple-publisher:
    build:
      context: simple-publisher
    depends_on:
      - redis
    networks:
      main: null

  simple-consumer:
    build:
      context: simple-consumer
    depends_on:
      - simple-publisher
    networks:
      main: null
